# Generated by Django 4.2.7 on 2025-09-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='doc_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
