# Generated by Django 4.2.7 on 2025-09-30 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=20)),
                ('doc_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('result_message', models.TextField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('request_ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verification_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_details', models.JSONField(blank=True, null=True)),
                ('document_preview_url', models.URLField(blank=True, null=True)),
                ('download_url', models.URLField(blank=True, null=True)),
                ('verification_metadata', models.JSONField(blank=True, null=True)),
                ('verification_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='verification.verificationrequest')),
            ],
            options={
                'db_table': 'verification_results',
            },
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('verification_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='verification.verificationrequest')),
            ],
            options={
                'db_table': 'verification_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
