# Generated by Django 4.2.7 on 2025-09-30 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('company', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'issuers',
            },
        ),
        migrations.CreateModel(
            name='IssuerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_authorizations', models.PositiveIntegerField(default=1000)),
                ('auto_approve', models.BooleanField(default=False)),
                ('require_verification', models.BooleanField(default=True)),
                ('notification_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('settings_json', models.JSONField(blank=True, default=dict)),
                ('issuer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='issuer.issuer')),
            ],
            options={
                'db_table': 'issuer_settings',
            },
        ),
        migrations.CreateModel(
            name='IssuerAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('authorize', 'Authorize Employee'), ('verify', 'Verify Document'), ('view_profile', 'View Employee Profile'), ('download_document', 'Download Document'), ('revoke_access', 'Revoke Access')], max_length=30)),
                ('emp_id', models.CharField(blank=True, max_length=20, null=True)),
                ('user_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('doc_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='issuer.issuer')),
            ],
            options={
                'db_table': 'issuer_access_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='IssuerAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=20)),
                ('user_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('permission_granted', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_authorizations', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to=settings.AUTH_USER_MODEL)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='issuer.issuer')),
            ],
            options={
                'db_table': 'issuer_authorizations',
                'ordering': ['-created_at'],
                'unique_together': {('issuer', 'emp_id', 'user_hash')},
            },
        ),
    ]
