# Generated by Django 5.2.6 on 2025-10-03 12:46

import documents.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrecord',
            name='file',
            field=models.FileField(blank=True, help_text='Uploaded document file', null=True, storage=documents.storage.DocumentStorage(), upload_to='documents/'),
        ),
    ]
