# Generated by Django 5.2.6 on 2025-10-05 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentrecord_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentrecord',
            name='file',
        ),
    ]
