# Generated by Django 4.2.7 on 2025-10-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_remove_documentrecord_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrecord',
            name='salt',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
