# Generated by Django 4.2.7 on 2025-10-06 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_documentrecord_salt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentrecord',
            name='salt',
        ),
    ]
